export {
  CONFIG_VERSION,
  MAX_MONITORS,
  MAX_GAMES,
  MAX_TABLE_DISPLAYS,
  MONITOR_SLOTS,
  TABLE_SLOTS,
  GAME_NUMBERS,
  TABLE_NUMBERS,
  createEmptyConfig,
  DEFAULT_UI_THEME,
  UI_THEME_IDS,
  UI_THEME_OPTIONS,
  applyDocumentTheme,
  isUiThemeId,
  normalizeUiTheme,
  DEFAULT_SOUND_VOLUME,
  normalizeSoundVolume,
  type AppConfig,
  type AppSnapshot,
  type DisplayBounds,
  type DisplayInfo,
  type GameSession,
  type MonitorMapping,
  type MonitorSlot,
  type TableSlot,
  type GameNumber,
  type TableNumber,
  type UiThemeId,
} from "../../shared/types";
